FROM ubuntu:23.10
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
RUN useradd -ms /bin/bash BuildUser
USER root
LABEL org.opencontainers.image.source="https://github.com/pcs3rd/docker-build-environments"

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'BuildUser:BuildUser' | chpasswd
RUN ssh-keygen -A


COPY ./scripts/halium_install_deps.sh /root/install_deps.sh 
RUN bash /root/install_deps.sh && rm /root/install_deps.sh

USER BuildUser
COPY ./scripts/halium_home_init.sh /home/BuildUser/home_init.sh
RUN bash /home/BuildUser/home_init.sh && rm /home/BuildUser/home_init.sh
RUN export PATH="$HOME/bin:$PATH" >> ~/.bashrc
RUN echo 'BuildUser:BuildUser' | chpasswd

USER root
EXPOSE 22
#CMD ["/usr/sbin/sshd","-D"]
#CMD ["/usr/sbin/sshd"]
