env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
      Build-kasm-plugin-host:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.TOKEN}}
          - name: 'Build Docker Image'
            run: |
              docker build . --tag ghcr.io/pcs3rd/Ubuntu-halium-build-env:23.10 -f dockerfile-ubuntu-halium
          - name: 'Push kasm-pipewire-plugin-host to ghcr.io'
            run: |
              docker push ghcr.io/pcs3rd/Ubuntu-halium-build-env:23.10
